layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: stars
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 6
  exclude:
    archived: false
    forks: true
    projects:
    # - repo-name

#social_media:  
  # twitter: @pollicipes
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  # linkedin: your_username
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  # 
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username
  
topics:

  - name: eDNA
  
  
  - name: Shiny
    web_url: https://github.com/topics/shiny
    image_url: https://raw.githubusercontent.com/rstudio/shiny/master/man/figures/logo.png

  
  - name: CSS Rmarkdown
    web_url: https://github.com/topics/xaringan
    image_url: https://user-images.githubusercontent.com/163582/45438104-ea200600-b67b-11e8-80fa-d9f2a99a03b0.png

  - name: All things R
    web_url: https://github.com/topics/r
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/r/r.png


